git mv Alipay.png                          alipay.png
git mv Amazon.png                          amazon.png
git mv American-Express.png                americanexpress.png
git mv Bancontact.png                      bancontact.png
git mv BCC.png                             bcc.png
git mv Bitcoin.png                         bitcoin.png
git mv Boleto.png                          boleto.png
git mv Carte-Bleue.png                     cartebleue.png
git mv Cirrus.png                          cirrus.png
git mv Citi-Bank.png                       citibank.png
git mv Click-and-Buy.png                   clickandbuy.png
git mv Delta.png                           delta.png
git mv DineroMail.png                      dineromail.png
git mv DinersClub.png                      dinersclub.png
git mv DirectDebit.png                     directdebit.png
git mv Discover.png                        discover.png
git mv DotPay.png                          dotpay.png
git mv EBAY.png                            ebay.png
git mv ECO.png                             eco.png
git mv Epay.png                            epay.png
git mv EPS.png                             eps.png
git mv Eway.png                            eway.png
git mv GiroPay.png                         giropay.png
git mv HSBC.png                            hsbc.png
git mv iDeal.png                           ideal.png
git mv JCB.png                             jcb.png
git mv Maestro-#1.png                      maestro1.png
git mv Maestro-#2.png                      maestro2.png
git mv OK-Pay.png                          okpay.png
git mv Payoneer.png                        payoneer.png
git mv PayPal.png                          paypal.png
git mv PayPoint.png                        paypoint.png
git mv Payza.png                           payza.png
git mv Pick-n-Pay.png                      picknpay.png
git mv PostePay.png                        postepay.png
git mv Przelewy24.png                      przelewy24.png
git mv Sage.png                            sage.png
git mv Skrill.png                          skrill.png
git mv Switch#1.png                        switch1.png
git mv Switch#2.png                        switch2.png
git mv todoCash.png                        todocash.png
git mv Ukash.png                           ukash.png
git mv UnionPay.png                        unionpay.png
git mv Verified-by-VISA.png                verifiedbyvisa.png
git mv Visa.png                            visa.png
git mv WebMoney.png                        webmoney.png
git mv Western-Union.png                   westernunion.png
git mv Wirecard.png                        wirecard.png
git mv WorldPay.png                        worldpay.png
git mv Yandex-Money.png                    yandexmoney.png
